package com.github.skjolber.packing.comparator;

import com.github.skjolber.packing.api.Placement;
import com.github.skjolber.packing.comparator.placement.PlacementComparator;

/**
 * Base class for chained {@link PlacementComparator} implementations.
 *
 * <p>Each subclass encapsulates one comparison dimension. When the dimension does not produce a
 * decisive result (returns 0), evaluation is forwarded to {@link #next}. The chain terminates
 * with {@code next == null}, which causes {@link #chain} to return 0.
 *
 * <p>Subclasses are generated by {@link com.github.skjolber.packing.comparator.placement.DefaultPlacementComparatorFactory}.
 * Custom comparators can also extend this class directly.
 */
public abstract class AbstractChainedPlacementComparator implements PlacementComparator {

	/** The next comparator in the chain, or {@code null} if this is the last step. */
	protected final PlacementComparator next;

	protected AbstractChainedPlacementComparator(PlacementComparator next) {
		this.next = next;
	}

	/** Returns the next comparator in the chain, or {@code null} if this is the last step. */
	public final PlacementComparator getNext() {
		return next;
	}

	/**
	 * Delegates to {@link #next}, or returns 0 if there is no next comparator.
	 *
	 * @param a the first placement
	 * @param b the second placement
	 * @return the result of the next comparator in the chain, or 0
	 */
	protected final int chain(Placement a, Placement b) {
		return next != null ? next.compare(a, b) : 0;
	}
}
