<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.github.skjolber.3d-bin-container-packing</groupId>
		<artifactId>parent</artifactId>
		<version>4.2.2-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>
	<artifactId>validators</artifactId>
	<name>validators</name>
	<description>Validators for 3D bin packaging results</description>

	<properties>
		<module-name>com.github.skjolber.packing.validators</module-name>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.github.skjolber.3d-bin-container-packing</groupId>
			<artifactId>api</artifactId>
		</dependency>
		<dependency>
			<groupId>com.github.skjolber.3d-bin-container-packing</groupId>
			<artifactId>test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
