---
openapi: 3.0.0
info:
  title: Pack API reference
  description: |
    Pack boxes into containers
  version: 1.0.0
paths:
  /pack:
    post:
      summary: Perform a packaging operation
      description: |
        Pack an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PackRequest"
      responses:
        "200":
          description: Pack response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PackResponse"

components:
  schemas:
    Surface:
      type: string
      enum:
        - front
        - frontAtZeroDegrees
        - frontAtNinetyDegrees
        - rear
        - rearAtZeroDegrees
        - rearAtNinetyDegrees
        - left
        - leftAtZeroDegrees
        - leftAtNinetyDegrees
        - right
        - rightAtZeroDegrees
        - rightAtNinetyDegrees
        - top
        - topAtZeroDegrees
        - topAtNinetyDegrees
        - bottom
        - bottomAtZeroDegrees
        - bottomAtNinetyDegrees
        - all

    PackedContainer:
      type: object
      properties:
        id:
          type: string
        weight:
          type: integer

    PackedBox:
      type: object
      properties:
        id:
          type: string
        x:
          type: integer
        y:
          type: integer
        z:
          type: integer
        surface:
          $ref: '#/components/schemas/Surface'

    Box:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        dx:
          type: integer
        dy:
          type: integer
        dz:
          type: integer
        surfaces:
          type: array
          items: 
            $ref: '#/components/schemas/Surface'

    Container:
      type: object
      properties:
        id:
          type: string
        dx:
          type: integer
        dy:
          type: integer
        dz:
          type: integer
        loadDx:
          type: integer
        loadDy:
          type: integer
        loadDz:
          type: integer
        minLoadWeight:
          type: integer
        maxLoadWeight:
          type: integer
        emptyWeight:
          type: integer

    ContainerItem:
      type: object    
      properties:
        container:
          $ref: '#/components/schemas/Container'
        count:
          type: integer
        cost:
          $ref: '#/components/schemas/Cost'

    BoxItem:
      type: object    
      properties:
        box:
          $ref: '#/components/schemas/Box'
        count:
          type: integer

    Packager:
      type: object
      properties:
        id:
          type: string
        resourceLimits:
          type: array
          items:
            $ref: '#/components/schemas/ResourceLimit'
        features:
          type: array
          items:
            $ref: '#/components/schemas/PackagerFeature'
          
    PackResult:
      type: object
      properties:
        container:
          $ref: '#/components/schemas/PackedContainer'
        boxes:
          type: array
          items:
            $ref: '#/components/schemas/PackedBox'

    PackResponse:
      type: object
      properties:
        status:
          type: integer
        results:
          type: array
          items:
            $ref: '#/components/schemas/PackResult'
            
    PackRequest:
      type: object
      properties:
        temporalLimit:
           $ref: '#/components/schemas/TemporalLimit'
        resourceLimits:
          type: array
          items:
            $ref: '#/components/schemas/ResourceLimit'
        maxContainers:
          type: integer
        containerItems:
          type: array
          items:
            $ref: '#/components/schemas/ContainerItem'
        boxItems:
          type: array
          items:
            $ref: '#/components/schemas/BoxItem'
        packagers:
          type: array
          items:
            $ref: '#/components/schemas/Packager'

    TemporalLimit:
      type: object
      properties:
        value:
          type: integer
          format: int64
        type:
          $ref: '#/components/schemas/TemporalLimitType'

    TemporalLimitType:
      type: string
      enum:
        - duration
        - deadline
            
    ResourceLimit:
      type: object
      properties:
        value:
          type: integer
          format: int64
        type:
          $ref: '#/components/schemas/ResourceLimitType'
            
    ResourceLimitType:
      type: string
      enum:
        - CPU_COUNT
        - CPU_TIME
        - CPU_COST

    PackagerFeature:
      type: object
      properties:
        name: 
          type: string

    Cost:
      type: object
      discriminator:
        propertyName: type
        mapping:
          fixed: "#/components/schemas/FixedCost"
          variable: "#/components/schemas/VariableCost"
      properties:
        name: 
          type: string

    FixedCost:
      allOf:
        - $ref: "#/components/schemas/Cost"
        - type: object    
          properties:
            value:
              type: integer
              format: int64

    VariableCost:
      allOf:
        - $ref: "#/components/schemas/Cost"
        - type: object    
          properties:
            name: 
              type: string
            weight:
              $ref: '#/components/schemas/WeightCost'

    WeightCost:
      type: object
      discriminator:
        propertyName: type
        mapping:
          unit: "#/components/schemas/WeightUnitCost"
          table: "#/components/schemas/WeightTableCost"
      properties:
        inclusive:
          type: boolean

    WeightUnitCost:
      allOf:
        - $ref: "#/components/schemas/WeightCost"
        - type: object    
          properties:
            startCost:
              type: integer
              format: int64
            startWeight:
              type: integer
              format: int64
            weight:
              type: integer
              format: int64
            cost:
              type: integer
              format: int64

    WeightTableCost:
      allOf:
        - $ref: "#/components/schemas/WeightCost"
        - type: object
          properties:
            table:
              type: array
              items:
                $ref: '#/components/schemas/WeightTableCostItem'

    WeightTableCostItem:
      type: object
      properties:
        weight:
          type: integer
          format: int64
        cost:
          type: integer
          format: int64
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          







