# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: NPM build

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 22 ]
    name: Node ${{ matrix.node }} build
    steps:
      - uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
      - run: |
          cd visualizer/viewer
          npm ci
      - run: |
          cd visualizer/viewer
          npm build

